"""reserve budgets and persist provider requests

Revision ID: 45c099340bb0
Revises: 9bff6ad13263
Create Date: 2026-09-26 16:54:58.522016+08:00

"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "45c099340bb0"
down_revision: Union[str, None] = "9bff6ad13263"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "provider_requests",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("operation_key", sa.String(length=120), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("idempotency_key", sa.String(length=64), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("owner_token", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["run_id"], ["pipeline_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key", name="uq_provider_request_key"),
    )
    op.create_index(
        "idx_requests_project_status", "provider_requests", ["project_id", "status"], unique=False
    )
    op.add_column("api_call_logs", sa.Column("request_id", sa.String(length=36), nullable=True))
    op.add_column("api_call_logs", sa.Column("call_no", sa.Integer(), server_default="1", nullable=False))
    op.add_column(
        "api_call_logs", sa.Column("status", sa.String(length=20), server_default="calling", nullable=False)
    )
    op.add_column("api_call_logs", sa.Column("provider_task_id", sa.String(length=200), nullable=True))
    op.add_column("api_call_logs", sa.Column("idempotency_key", sa.String(length=64), nullable=True))
    op.add_column(
        "api_call_logs", sa.Column("quoted_cents", sa.Integer(), server_default="0", nullable=False)
    )
    op.add_column(
        "api_call_logs", sa.Column("reserved_cents", sa.Integer(), server_default="0", nullable=False)
    )
    op.add_column("api_call_logs", sa.Column("reported_cost_cents", sa.Integer(), nullable=True))
    op.add_column("api_call_logs", sa.Column("response", sa.JSON(), nullable=True))
    op.add_column("api_call_logs", sa.Column("finished_at", sa.DateTime(), nullable=True))
    op.create_unique_constraint("uq_calls_request_no", "api_call_logs", ["request_id", "call_no"])
    op.create_foreign_key(
        "fk_calls_request", "api_call_logs", "provider_requests", ["request_id"], ["id"], ondelete="CASCADE"
    )
    op.add_column(
        "budget_ledger", sa.Column("reserved_cents", sa.Integer(), server_default="0", nullable=False)
    )
    op.create_check_constraint(
        "ck_budget_available",
        "budget_ledger",
        "spent_cents >= 0 AND reserved_cents >= 0 AND spent_cents + reserved_cents <= budget_cents",
    )
    op.execute(
        "UPDATE api_call_logs SET status = CASE WHEN success = 1 THEN 'succeeded' ELSE 'failed' END, "
        "reported_cost_cents = cost_cents WHERE request_id IS NULL"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_budget_available", "budget_ledger", type_="check")
    op.drop_column("budget_ledger", "reserved_cents")
    op.drop_constraint("fk_calls_request", "api_call_logs", type_="foreignkey")
    op.drop_constraint("uq_calls_request_no", "api_call_logs", type_="unique")
    op.drop_column("api_call_logs", "finished_at")
    op.drop_column("api_call_logs", "response")
    op.drop_column("api_call_logs", "reported_cost_cents")
    op.drop_column("api_call_logs", "reserved_cents")
    op.drop_column("api_call_logs", "quoted_cents")
    op.drop_column("api_call_logs", "idempotency_key")
    op.drop_column("api_call_logs", "provider_task_id")
    op.drop_column("api_call_logs", "status")
    op.drop_column("api_call_logs", "call_no")
    op.drop_column("api_call_logs", "request_id")
    op.drop_table("provider_requests")
    # ### end Alembic commands ###
