"""version storyboard and review reference assets

Revision ID: f6b6201f6705
Revises: 45c099340bb0
Create Date: 2026-09-26 17:35:05.511030+08:00

"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f6b6201f6705"
down_revision: Union[str, None] = "45c099340bb0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("character_refs", sa.Column("uploaded_anchor_version", sa.Integer(), nullable=False, server_default="1"))
    op.add_column("character_refs", sa.Column("reviewed_anchor_version", sa.Integer(), nullable=True))
    op.add_column("character_refs", sa.Column("reviewed_by", sa.String(length=80), nullable=True))
    op.add_column("character_refs", sa.Column("reviewed_at", sa.DateTime(), nullable=True))
    op.add_column("character_refs", sa.Column("review_note", sa.Text(), nullable=True))
    op.add_column("character_refs", sa.Column("review_version", sa.Integer(), nullable=False, server_default="0"))
    op.create_unique_constraint("uq_refs_character_hash", "character_refs", ["character_id", "asset_sha256"])
    op.add_column("projects", sa.Column("storyboard_version", sa.Integer(), nullable=False, server_default="1"))
    op.execute("UPDATE character_refs r JOIN characters c ON c.id = r.character_id "
               "SET r.uploaded_anchor_version = c.anchor_version, r.qc_passed = 0, r.is_primary = 0")
    op.alter_column("character_refs", "uploaded_anchor_version", existing_type=sa.Integer(), server_default=None)
    op.alter_column("character_refs", "review_version", existing_type=sa.Integer(), server_default=None)
    op.alter_column("projects", "storyboard_version", existing_type=sa.Integer(), server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "storyboard_version")
    op.drop_constraint("uq_refs_character_hash", "character_refs", type_="unique")
    op.drop_column("character_refs", "review_version")
    op.drop_column("character_refs", "review_note")
    op.drop_column("character_refs", "reviewed_at")
    op.drop_column("character_refs", "reviewed_by")
    op.drop_column("character_refs", "reviewed_anchor_version")
    op.drop_column("character_refs", "uploaded_anchor_version")
    # ### end Alembic commands ###
