"""initial catalog schema

Revision ID: 9bff6ad13263
Revises:
Create Date: 2026-09-26 16:14:17.704948+08:00

"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9bff6ad13263"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_call_logs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=True),
        sa.Column("shot_id", sa.String(length=36), nullable=True),
        sa.Column("attempt_id", sa.String(length=36), nullable=True),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("model", sa.String(length=80), nullable=False),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("cost_cents", sa.Integer(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("error_code", sa.String(length=60), nullable=True),
        sa.Column("is_retry", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_calls_project_time", "api_call_logs", ["project_id", "created_at"], unique=False)
    op.create_index("idx_calls_provider", "api_call_logs", ["provider", "model", "success"], unique=False)
    op.create_index(op.f("ix_api_call_logs_created_at"), "api_call_logs", ["created_at"], unique=False)
    op.create_table(
        "projects",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("synopsis", sa.Text(), nullable=True),
        sa.Column("style", sa.String(length=80), nullable=False),
        sa.Column("global_negative_prompt", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("budget_cents", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "qc_golden_set",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("asset_key", sa.String(length=64), nullable=False),
        sa.Column("asset_path", sa.String(length=500), nullable=False),
        sa.Column("character_id", sa.String(length=36), nullable=True),
        sa.Column("label", sa.String(length=30), nullable=False),
        sa.Column("label_detail", sa.JSON(), nullable=True),
        sa.Column("labeled_by", sa.String(length=80), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("asset_key", name="uq_golden_asset"),
    )
    op.create_index("idx_golden_label", "qc_golden_set", ["label"], unique=False)
    op.create_table(
        "budget_ledger",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("scope", sa.String(length=20), nullable=False),
        sa.Column("scope_key", sa.String(length=120), nullable=False),
        sa.Column("budget_cents", sa.Integer(), nullable=False),
        sa.Column("spent_cents", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "scope", "scope_key", name="uq_budget_scope"),
    )
    op.create_index(op.f("ix_budget_ledger_project_id"), "budget_ledger", ["project_id"], unique=False)
    op.create_table(
        "characters",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("face_features", sa.JSON(), nullable=False),
        sa.Column("hair_features", sa.JSON(), nullable=False),
        sa.Column("body_features", sa.JSON(), nullable=False),
        sa.Column("outfit_features", sa.JSON(), nullable=False),
        sa.Column("style_lock", sa.JSON(), nullable=False),
        sa.Column("anchor_prompt", sa.Text(), nullable=False),
        sa.Column("anchor_version", sa.Integer(), nullable=False),
        sa.Column("confirmed", sa.Boolean(), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "name", name="uq_characters_project_name"),
    )
    op.create_index(op.f("ix_characters_project_id"), "characters", ["project_id"], unique=False)
    op.create_table(
        "exports",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=True),
        sa.Column("output_path", sa.String(length=500), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("resolution", sa.String(length=20), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_exports_project", "exports", ["project_id"], unique=False)
    op.create_index(op.f("ix_exports_project_id"), "exports", ["project_id"], unique=False)
    op.create_table(
        "pipeline_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("graph_state", sa.JSON(), nullable=False),
        sa.Column("current_stage", sa.String(length=40), nullable=True),
        sa.Column("spent_cents", sa.Integer(), nullable=False),
        sa.Column("error_code", sa.String(length=60), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_runs_project_status", "pipeline_runs", ["project_id", "status"], unique=False)
    op.create_index(op.f("ix_pipeline_runs_project_id"), "pipeline_runs", ["project_id"], unique=False)
    op.create_table(
        "scenes",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("location", sa.String(length=200), nullable=False),
        sa.Column("time_of_day", sa.String(length=40), nullable=False),
        sa.Column("mood", sa.String(length=80), nullable=False),
        sa.Column("background_prompt", sa.Text(), nullable=True),
        sa.Column("baseline_attempt_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "seq", name="uq_scenes_project_seq"),
    )
    op.create_index(op.f("ix_scenes_project_id"), "scenes", ["project_id"], unique=False)
    op.create_table(
        "character_refs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("character_id", sa.String(length=36), nullable=False),
        sa.Column("ref_type", sa.String(length=40), nullable=False),
        sa.Column("asset_path", sa.String(length=500), nullable=False),
        sa.Column("asset_sha256", sa.String(length=64), nullable=True),
        sa.Column("ref_weight", sa.Float(), nullable=False),
        sa.Column("qc_passed", sa.Boolean(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["character_id"], ["characters.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_character_refs_character_id"), "character_refs", ["character_id"], unique=False)
    op.create_table(
        "review_gates",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("gate_type", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("reviewer", sa.String(length=80), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("snapshot", sa.JSON(), nullable=False),
        sa.Column("decided_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["pipeline_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_gates_run", "review_gates", ["run_id", "gate_type"], unique=False)
    op.create_index(op.f("ix_review_gates_run_id"), "review_gates", ["run_id"], unique=False)
    op.create_table(
        "shots",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("scene_id", sa.String(length=36), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("shot_size", sa.String(length=20), nullable=False),
        sa.Column("camera_move", sa.String(length=40), nullable=True),
        sa.Column("composition", sa.Text(), nullable=False),
        sa.Column("character_ids", sa.JSON(), nullable=False),
        sa.Column("action_text", sa.Text(), nullable=False),
        sa.Column("dialogue", sa.Text(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("negative_prompt", sa.Text(), nullable=True),
        sa.Column("prev_locked_attempt_id", sa.String(length=36), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("max_retry", sa.Integer(), nullable=False),
        sa.Column("locked_attempt_id", sa.String(length=36), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("max_retry >= 0", name="ck_shots_max_retry"),
        sa.ForeignKeyConstraint(["scene_id"], ["scenes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scene_id", "seq", name="uq_shots_scene_seq"),
    )
    op.create_index("idx_shots_status", "shots", ["status"], unique=False)
    op.create_index(op.f("ix_shots_scene_id"), "shots", ["scene_id"], unique=False)
    op.create_table(
        "render_attempts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("shot_id", sa.String(length=36), nullable=False),
        sa.Column("attempt_no", sa.Integer(), nullable=False),
        sa.Column("stage", sa.String(length=20), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("model", sa.String(length=80), nullable=False),
        sa.Column("seed", sa.String(length=80), nullable=True),
        sa.Column("request_payload", sa.JSON(), nullable=False),
        sa.Column("anchor_version", sa.Integer(), nullable=True),
        sa.Column("asset_path", sa.String(length=500), nullable=True),
        sa.Column("asset_sha256", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error_code", sa.String(length=60), nullable=True),
        sa.Column("cost_cents", sa.Integer(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("idempotency_key", sa.String(length=64), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["shot_id"], ["shots.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key", name="uq_attempts_idempotency"),
        sa.UniqueConstraint("shot_id", "attempt_no", name="uq_attempts_shot_no"),
    )
    op.create_index("idx_attempts_shot_stage", "render_attempts", ["shot_id", "stage"], unique=False)
    op.create_index("idx_attempts_status", "render_attempts", ["status"], unique=False)
    op.create_index(op.f("ix_render_attempts_shot_id"), "render_attempts", ["shot_id"], unique=False)
    op.create_table(
        "qc_reports",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("attempt_id", sa.String(length=36), nullable=False),
        sa.Column("model", sa.String(length=80), nullable=False),
        sa.Column("verdict", sa.String(length=20), nullable=False),
        sa.Column("dimensions", sa.JSON(), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=True),
        sa.Column("suggestion", sa.String(length=40), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("reasoning", sa.Text(), nullable=True),
        sa.Column("raw_response", sa.JSON(), nullable=False),
        sa.Column("human_verdict", sa.String(length=20), nullable=True),
        sa.Column("human_note", sa.Text(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["attempt_id"], ["render_attempts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_qc_attempt", "qc_reports", ["attempt_id"], unique=False)
    op.create_index("idx_qc_verdict", "qc_reports", ["verdict"], unique=False)
    op.create_index(op.f("ix_qc_reports_attempt_id"), "qc_reports", ["attempt_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # 删除表会一并移除索引；MySQL 不允许先删仍被外键使用的索引。
    for table in (
        "qc_reports", "render_attempts", "shots", "review_gates", "character_refs",
        "scenes", "pipeline_runs", "exports", "characters", "budget_ledger",
        "qc_golden_set", "projects", "api_call_logs",
    ):
        op.drop_table(table)
